package org.whl.bookcapture

/**
 * The desktop's cross-database matcher, ported to run on the phone.
 *
 * The acceptance thresholds in `catalog_checks.py` were tuned against
 * `difflib.SequenceMatcher.ratio()`, so they only mean the same thing here if
 * this reproduces that function exactly — an approximation would silently shift
 * every decision boundary. `ChMatcherConformanceTest` checks this against
 * ratios generated by the real Python for ~800 pairs, including degenerate
 * inputs and the hard negatives where two different books share a prefix.
 *
 * Everything is pure and allocation-light: it runs on the scan path, over a
 * 5264-row index, on a phone.
 */
object ChMatcher {

    /** Mirrors whl_client._normalize: lowercase, non-alphanumerics to a single
     *  space, collapsed and trimmed. */
    fun normalize(text: String?): String {
        if (text.isNullOrEmpty()) return ""
        val out = StringBuilder(text.length)
        var pendingSpace = false
        for (raw in text) {
            val ch = raw.lowercaseChar()
            if (ch in 'a'..'z' || ch in '0'..'9') {
                if (pendingSpace && out.isNotEmpty()) out.append(' ')
                pendingSpace = false
                out.append(ch)
            } else {
                // Any run of non-alphanumerics collapses to one space, and a
                // leading or trailing run disappears entirely.
                pendingSpace = true
            }
        }
        return out.toString()
    }

    /** Tails that are credentials, not given names, so "Last, <tail>" must not flip. */
    private val AUTHOR_SUFFIXES = setOf(
        "jr", "sr", "ii", "iii", "iv", "md", "phd", "do", "esq",
        "ma", "ba", "bsc", "msc", "praeses", "respondent",
    )

    /** Mirrors whl_client.flip_author. */
    fun flipAuthor(name: String?): String {
        val s = (name ?: "").trim()
        if (s.count { it == ',' } != 1) return s
        val comma = s.indexOf(',')
        val last = s.substring(0, comma).trim()
        val first = s.substring(comma + 1).trim()
        if (last.isEmpty() || first.isEmpty()) return s
        val bare = first.lowercase().filter { it in 'a'..'z' }
        if (bare in AUTHOR_SUFFIXES) return s
        return "$first $last"
    }

    /** Mirrors catalog_checks.author_tokens: len>=4, minus stopwords. */
    fun authorTokens(author: String?, stop: Set<String>): Set<String> =
        normalize(flipAuthor(author))
            .split(' ')
            .filter { it.length >= 4 && it !in stop }
            .toSet()

    /** Mirrors catalog_checks.last_token. */
    fun lastToken(author: String?): String =
        normalize(flipAuthor(author)).split(' ').lastOrNull { it.length >= 3 } ?: ""

    // --- difflib.SequenceMatcher ------------------------------------------
    //
    // ratio() is 2*M/T where M is the total size of the matching blocks and T
    // the combined length. Only the TOTAL is needed, so the blocks are summed
    // as they are found rather than collected, sorted and merged.

    /**
     * Total matched elements, following difflib's recursive
     * longest-matching-block decomposition.
     *
     * `isjunk` is None in every call site, so the junk-extension passes in
     * find_longest_match are unreachable and are omitted. The AUTOJUNK
     * heuristic is NOT omitted: it engages at 200+ elements, and CH's longest
     * title is 212 characters, so it genuinely fires on real data. Dropping it
     * would make long titles disagree with the desktop.
     */
    private fun matchedTotal(a: String, b: String): Int {
        if (a.isEmpty() || b.isEmpty()) return 0

        val b2j = HashMap<Char, MutableList<Int>>(b.length * 2)
        for (j in b.indices) b2j.getOrPut(b[j]) { ArrayList() }.add(j)

        // difflib: for n >= 200, elements occurring more than n/100+1 times are
        // treated as popular and removed from the index entirely.
        val n = b.length
        if (n >= 200) {
            val ntest = n / 100 + 1
            val popular = b2j.entries.filter { it.value.size > ntest }.map { it.key }
            for (key in popular) b2j.remove(key)
        }

        var total = 0
        // (alo, ahi, blo, bhi) ranges still to decompose.
        val queue = ArrayDeque<IntArray>()
        queue.addLast(intArrayOf(0, a.length, 0, b.length))
        while (queue.isNotEmpty()) {
            val (alo, ahi, blo, bhi) = queue.removeLast()

            var besti = alo
            var bestj = blo
            var bestsize = 0
            var j2len = HashMap<Int, Int>()

            for (i in alo until ahi) {
                val newj2len = HashMap<Int, Int>()
                val positions = b2j[a[i]]
                if (positions != null) {
                    for (j in positions) {
                        if (j < blo) continue
                        if (j >= bhi) break
                        val k = (j2len[j - 1] ?: 0) + 1
                        newj2len[j] = k
                        if (k > bestsize) {
                            besti = i - k + 1
                            bestj = j - k + 1
                            bestsize = k
                        }
                    }
                }
                j2len = newj2len
            }

            // Extend across elements that are equal but were pruned from b2j
            // as popular; difflib does this so a popular element inside an
            // otherwise-matching run is not lost.
            while (besti > alo && bestj > blo && a[besti - 1] == b[bestj - 1]) {
                besti--; bestj--; bestsize++
            }
            while (besti + bestsize < ahi && bestj + bestsize < bhi &&
                a[besti + bestsize] == b[bestj + bestsize]
            ) {
                bestsize++
            }

            if (bestsize > 0) {
                total += bestsize
                if (alo < besti && blo < bestj) {
                    queue.addLast(intArrayOf(alo, besti, blo, bestj))
                }
                if (besti + bestsize < ahi && bestj + bestsize < bhi) {
                    queue.addLast(intArrayOf(besti + bestsize, ahi, bestj + bestsize, bhi))
                }
            }
        }
        return total
    }

    /** difflib.SequenceMatcher(None, a, b).ratio() over already-normalized text. */
    fun ratio(a: String, b: String): Double {
        val length = a.length + b.length
        // difflib returns 1.0 for two empty sequences, not 0.0.
        if (length == 0) return 1.0
        return 2.0 * matchedTotal(a, b) / length
    }

    /** whl_client.similarity. */
    fun similarity(a: String?, b: String?): Double = ratio(normalize(a), normalize(b))

    /** whl_client.similarity_prefix. */
    fun similarityPrefix(a: String?, b: String?, n: Int): Double =
        ratio(normalize(a).take(n), normalize(b).take(n))

    /**
     * catalog_checks.title_author_match.
     *
     * Title-forward: a strong leading-title match, confirmed by a full-title
     * ratio whose bar depends on author agreement — lenient when a surname is
     * shared, strict when the authors look different, which is what stops two
     * same-prefix books by different authors from collapsing together.
     */
    fun titleAuthorMatch(
        title: String,
        author: String,
        candTitle: String,
        candAuthor: String,
        config: ChIndexConfig,
    ): Boolean {
        if (similarityPrefix(title, candTitle, config.titlePrefix) < config.prefixMin) return false
        val full = similarity(title, candTitle)
        val ours = authorTokens(author, config.authorStop)
        val theirs = authorTokens(candAuthor, config.authorStop)
        if (ours.any { it in theirs }) return full >= config.fullMin
        if (ours.isEmpty() || theirs.isEmpty()) return full >= config.fullMissing
        return full >= config.fullStrict
    }
}

/** Thresholds and tuning carried by the index, so the phone never hardcodes
 *  values the desktop owns. */
data class ChIndexConfig(
    val bucketChars: Int,
    val titlePrefix: Int,
    val prefixMin: Double,
    val fullMin: Double,
    val fullMissing: Double,
    val fullStrict: Double,
    val authorStop: Set<String>,
)
