-- Library Tool cloud — schema entry point.
--
-- The schema ships as ordered, append-only migrations:
--
--     docs/cloud/migrations/001_baseline.sql
--     docs/cloud/migrations/NNN_<slug>.sql ...
--
-- Fresh project: paste every file into the Supabase SQL Editor and run it,
-- in order. Existing project: `python3 tools/cloud_setup.py check` diffs the
-- `schema_migrations` table against that directory and names the pending
-- files — paste those, in order. Every migration is idempotent and records
-- itself, so re-running one applies the difference and nothing else.
--
-- Writing a migration (docs/cloud/migrations/NNN_<slug>.sql):
--   * next NNN, append-only — never edit an applied file; to undo one,
--     ship a new migration that reverses it
--   * idempotent DDL only (`if not exists`, `drop policy if exists`, ...)
--   * explicit revoke/grant + RLS beside every new table (see 001_baseline;
--     service-role-only tables stay policy-free on purpose)
--   * end with:
--       insert into schema_migrations (id) values ('NNN_<slug>')
--       on conflict do nothing;
--
-- Afterwards:  python3 tools/cloud_setup.py check
