// GENERATED by scripts/gen-cloud-defaults.mjs from tools/cloud_defaults.py.
// Do not edit. Run `npm run build` (or node scripts/gen-cloud-defaults.mjs) to refresh.
// Public identifiers only — row-level security is what protects the project.
export const SUPABASE_URL = "https://vnjcocsyvshnbbwfblsp.supabase.co"
export const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZuamNvY3N5dnNobmJid2ZibHNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODM2NDg3MDQsImV4cCI6MjA5OTIyNDcwNH0.bQ9YOFntTfsbNngl5rcm4mB2DP7gq67zEPufdxHkzkI"
