"""Windows platform adapters for Library Tool engine ports."""

from .secret_store import (
    DataProtectorPort,
    FileProtectedBlobStore,
    ProtectedBlobStorePort,
    ProtectedBlobTransactionPort,
    ProtectedEnvelopeCredentialLease,
    ProtectedEnvelopeSecretStoreHealth,
    ProtectedEnvelopeSecretStoreRepository,
    SecretCredentialNotConfiguredError,
    SecretIdRegistry,
    SecretStoreAdapterError,
    SecretStoreCapacityError,
    SecretStoreCorruptError,
    SecretStoreEnvelopeLimits,
    SecretStoreHealth,
    SecretStoreHealthPort,
    SecretStoreHealthState,
    SecretStoreLockedOrUnreadableError,
    SecretStoreNewerSchemaError,
    SecretStoreUnavailableError,
    SecretStoreUnsupportedError,
    WindowsDpapiProtector,
    WindowsDpapiSecretStoreRepository,
)

__all__ = [
    "DataProtectorPort",
    "FileProtectedBlobStore",
    "ProtectedBlobStorePort",
    "ProtectedBlobTransactionPort",
    "ProtectedEnvelopeCredentialLease",
    "ProtectedEnvelopeSecretStoreHealth",
    "ProtectedEnvelopeSecretStoreRepository",
    "SecretCredentialNotConfiguredError",
    "SecretIdRegistry",
    "SecretStoreAdapterError",
    "SecretStoreCapacityError",
    "SecretStoreCorruptError",
    "SecretStoreEnvelopeLimits",
    "SecretStoreHealth",
    "SecretStoreHealthPort",
    "SecretStoreHealthState",
    "SecretStoreLockedOrUnreadableError",
    "SecretStoreNewerSchemaError",
    "SecretStoreUnavailableError",
    "SecretStoreUnsupportedError",
    "WindowsDpapiProtector",
    "WindowsDpapiSecretStoreRepository",
]
