#!/usr/bin/env python3
"""Git worktrees for this repo, set up so several sessions can run at once.

    python3 tools/worktree.py add <name>     create a worktree + branch
    python3 tools/worktree.py list           show them, with ports
    python3 tools/worktree.py rm <name>      remove one

Three things make a plain `git worktree add` unpleasant here, and this script
handles each of them.

DATA_ROOT.  The server writes its state (client_state.json, manual entries,
builds, downloads) under DATA_ROOT, which defaults to the repo root. Two
worktrees sharing a checkout would be fine, but two SERVERS writing the same
output/ would not: client_state is server-authoritative on load, and a second
instance has already cost this project its checked-book set once. Every worktree
therefore gets a private DATA_ROOT at .wt/data. ch_library.json still comes from
the worktree's own checkout via APP_ROOT, and the databases (the renewals CSV,
the WHL catalogue, the OL indexes) resolve most-accessible-first via find_db —
the shared ~/.library-tool drop-in, then DATA_ROOT, then the checkout — so the
app is fully functional against empty state.

PORT.  The server binds 5001 unless WHL_PORT says otherwise, so a second one
fails to start. Each worktree is assigned its own port and gets a .claude/
launch.json pointing at it, so `preview_start` works without collisions.

WEIGHT.  The corpus images under photo/ and books/ (273 MB that no code
reads) are untracked as of the corpus-leaves-git commit and sync via
tools/corpus_sync.py instead, so new checkouts are ~20 MB by default. The
sparse-checkout exclusion below still matters when a worktree is based on an
older commit that tracks them (pass --full to keep everything). Note the
pattern covers all of books/, so a sparse worktree also omits the tracked
books/*/transcript.txt OCR transcripts; --full restores those on any base.
"""
from __future__ import annotations

import argparse
import json
import os
import shutil
import socket
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
# Outside the repo on purpose: a worktree inside it would show up as an
# untracked directory in every `git status` of the parent.
WORKTREES = Path(os.environ.get("WHL_WORKTREES") or REPO.parent / "whl-worktrees")

PORT_BASE = 5101          # 5001 belongs to the main checkout
HEAVY = ["/photo/", "/books/"]

# Copied into a new worktree's DATA_ROOT by --seed. client_state.json carries
# API keys, so seeding is opt-in and never leaves this machine.
SEED_FILES = [
    "output/client_state.json",
    "output/manual_entries.json",
    "output/whl_builds.json",
    "output/whl_corrections.json",
    "downloads/ia/catalog.json",
]

SERVE_PY = '''\
"""Launcher for this worktree: its own port, its own DATA_ROOT.

Generated by tools/worktree.py. Not tracked -- edit freely.
"""
import os, runpy, sys
from pathlib import Path

here = Path(__file__).resolve().parent          # <worktree>/.wt
os.environ["WHL_PORT"] = "{port}"
os.environ["WHL_DATA_ROOT"] = str(here / "data")
sys.argv = ["server.py"]
runpy.run_path(str(here.parent / "tools" / "whl_explorer" / "server.py"),
               run_name="__main__")
'''


def git(*args: str, cwd: Path | None = None, check: bool = True) -> str:
    r = subprocess.run(["git", *args], cwd=str(cwd or REPO),
                       capture_output=True, text=True)
    if check and r.returncode != 0:
        sys.exit(f"git {' '.join(args)}\n{r.stderr.strip()}")
    return r.stdout.strip()


def worktrees() -> list[dict]:
    """Every worktree except the main checkout, with its port if it has one."""
    out, cur = [], {}
    for line in git("worktree", "list", "--porcelain").splitlines() + [""]:
        if not line:
            if cur.get("worktree"):
                out.append(cur)
            cur = {}
            continue
        k, _, v = line.partition(" ")
        cur[k] = v
    rows = []
    for w in out:
        p = Path(w["worktree"])
        if p == REPO:
            continue
        info = p / ".wt" / "info.json"
        port = None
        if info.is_file():
            try:
                port = json.loads(info.read_text(encoding="utf-8")).get("port")
            except ValueError:
                pass
        rows.append({"path": p, "branch": w.get("branch", "").replace("refs/heads/", ""),
                     "port": port})
    return rows


def free_port(taken: set[int]) -> int:
    for p in range(PORT_BASE, PORT_BASE + 50):
        if p in taken:
            continue
        with socket.socket() as s:
            if s.connect_ex(("127.0.0.1", p)) != 0:   # nothing listening
                return p
    sys.exit("no free port in %d..%d" % (PORT_BASE, PORT_BASE + 50))


def _assert_main_intact(name: str, path: Path) -> None:
    """Sparse-checkout leaking into the shared config empties the main checkout.

    It is a silent, 273 MB deletion, so verify rather than trust: the flag must
    not be in the main checkout's config, and the heavy directories must still
    be on disk. On failure, undo everything before returning the error.
    """
    leaked = git("config", "--local", "--get", "core.sparseCheckout", check=False)
    missing = [h.strip("/") for h in HEAVY if not (REPO / h.strip("/")).is_dir()]
    if not leaked and not missing:
        return
    git("worktree", "remove", "--force", str(path), check=False)
    git("branch", "-D", name, check=False)
    if leaked:
        git("sparse-checkout", "disable", check=False)
    if missing:
        git("checkout", "--", *missing, check=False)
    sys.exit(
        "ABORTED: sparse-checkout leaked into the main checkout"
        + (f" (core.sparseCheckout={leaked})" if leaked else "")
        + (f", emptying {', '.join(missing)}" if missing else "")
        + "\nThe worktree was removed and the main checkout restored."
        "\nRe-run with --full to skip sparse-checkout entirely."
    )


def cmd_list(_args) -> None:
    rows = worktrees()
    print(f"main  {REPO}  (port 5001)")
    if not rows:
        print("\nNo worktrees. Add one:  python3 tools/worktree.py add <name>")
        return
    print()
    for r in rows:
        size = sum(f.stat().st_size for f in r["path"].rglob("*")
                   if f.is_file() and ".git" not in f.parts) / 1e6
        print(f"{r['branch']:<18} port {r['port'] or '?':<6} {size:6.0f} MB  {r['path']}")


def cmd_add(args) -> None:
    name = args.name
    path = WORKTREES / name
    if path.exists():
        sys.exit(f"{path} already exists")
    if git("branch", "--list", name):
        sys.exit(f"branch {name!r} already exists (pick another name, or `git branch -d {name}`)")

    port = args.port or free_port({r["port"] for r in worktrees() if r["port"]})
    WORKTREES.mkdir(parents=True, exist_ok=True)

    # --no-checkout first: writing 330 MB and then deleting 273 MB of it is
    # slower than never writing it
    git("worktree", "add", "--no-checkout", "-b", name, str(path), args.base)
    if not args.full:
        # WITHOUT this, `git sparse-checkout init` writes core.sparseCheckout to
        # the SHARED config, and the main checkout starts honouring a pattern
        # file it does not have -- which silently deletes photo/ and books/ from
        # it. Ask me how I know. With it, both the flag and the patterns live
        # under .git/worktrees/<name>/.
        git("config", "extensions.worktreeConfig", "true")
        git("sparse-checkout", "init", "--no-cone", cwd=path)
        git("config", "--worktree", "core.sparseCheckout", "true", cwd=path)
        git("sparse-checkout", "set", "--no-cone", "/*", *[f"!{h}" for h in HEAVY], cwd=path)
    git("checkout", cwd=path)
    _assert_main_intact(name, path)

    wt = path / ".wt"
    (wt / "data").mkdir(parents=True, exist_ok=True)
    (wt / "serve.py").write_text(SERVE_PY.format(port=port), encoding="utf-8")
    (wt / "info.json").write_text(
        json.dumps({"name": name, "port": port, "base": args.base}, indent=2), encoding="utf-8")

    # preview_start reads this; the wrapper is what actually applies the port.
    # launch.json is gitignored, so writing it here leaves the branch clean --
    # an earlier attempt used `update-index --skip-worktree`, which cannot work:
    # that bit is the very mechanism sparse-checkout uses, and it resets it.
    (path / ".claude").mkdir(exist_ok=True)
    (path / ".claude" / "launch.json").write_text(json.dumps({
        "version": "0.0.1",
        "configurations": [{
            "name": "whl-explorer",
            "runtimeExecutable": "python3",
            "runtimeArgs": [".wt/serve.py"],
            "port": port,
            "autoPort": False,
        }],
    }, indent=2) + "\n", encoding="utf-8")

    if args.seed:
        for rel in SEED_FILES:
            src = REPO / rel
            if not src.is_file():
                continue
            dst = wt / "data" / rel
            dst.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(src, dst)
        print("seeded DATA_ROOT from the main checkout (includes API keys)")

    size = sum(f.stat().st_size for f in path.rglob("*")
               if f.is_file() and ".git" not in f.parts) / 1e6
    print(f"\n{name}  ->  {path}   ({size:.0f} MB, port {port})\n")
    print(f"  cd {path}")
    print( "  claude")
    print(f"\nIts server runs on {port} against .wt/data, so it cannot touch the")
    print( "main checkout's books or settings.")


def cmd_rm(args) -> None:
    path = WORKTREES / args.name
    if not path.exists():
        sys.exit(f"no worktree at {path}")
    # .wt/ is ignored, so a clean tree removes without --force
    cmd = ["worktree", "remove"] + (["--force"] if args.force else []) + [str(path)]
    git(*cmd)
    if args.delete_branch:
        git("branch", "-D", args.name)
        print(f"removed worktree and branch {args.name}")
    else:
        print(f"removed worktree {args.name} (branch kept; -d also deletes it)")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    sub = ap.add_subparsers(dest="cmd", required=True)

    sub.add_parser("list", help="show worktrees and their ports").set_defaults(fn=cmd_list)

    a = sub.add_parser("add", help="create a worktree + branch")
    a.add_argument("name")
    # main, not master: local master is the STALE pre-inversion line (see the
    # 2026-07-11 divergence note) — a worktree forked from it silently loses
    # every feature landed since, and the loss only surfaces when a function
    # you expect is missing.
    a.add_argument("--base", default="main", help="branch to fork from (default: main)")
    a.add_argument("--port", type=int, help="override the assigned port")
    a.add_argument("--full", action="store_true", help="check out photo/ and books/ too (tracked transcripts; +273 MB of images on pre-corpus-sync bases)")
    a.add_argument("--seed", action="store_true",
                   help="copy the main checkout's books and settings into this worktree's DATA_ROOT")
    a.set_defaults(fn=cmd_add)

    r = sub.add_parser("rm", help="remove a worktree")
    r.add_argument("name")
    r.add_argument("--force", action="store_true", help="discard uncommitted changes")
    r.add_argument("-d", "--delete-branch", action="store_true")
    r.set_defaults(fn=cmd_rm)

    args = ap.parse_args()
    args.fn(args)


if __name__ == "__main__":
    main()
