package org.whl.bookcapture

import org.json.JSONObject
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Pins the Kotlin matcher to the Python one.
 *
 * The acceptance thresholds in catalog_checks.py were tuned against
 * difflib.SequenceMatcher; if this port drifts from it, every CH decision
 * shifts silently and nothing else in the build would notice. The fixtures are
 * generated by tools/build_ch_index.py from the real CH list and the real
 * Python functions, so this compares against ground truth rather than against
 * a second guess at the same algorithm.
 *
 * Regenerate with:
 *   python3 tools/build_ch_index.py --out output \
 *     --fixtures android/BookCapture/app/src/test/resources/ch_match_fixtures.json
 */
class ChMatcherConformanceTest {

    private val fixtures: JSONObject by lazy {
        val stream = requireNotNull(
            javaClass.classLoader?.getResourceAsStream("ch_match_fixtures.json"),
        ) { "ch_match_fixtures.json missing — regenerate it with tools/build_ch_index.py" }
        JSONObject(stream.bufferedReader().use { it.readText() })
    }

    /** Ratios are compared exactly to 1e-12: this is deterministic integer
     *  arithmetic over a division, not a heuristic, so anything looser would
     *  hide a real divergence in the matching-block decomposition. */
    private val tolerance = 1e-12

    /** The tuning the fixtures were generated with, read from the fixtures so
     *  a retune on the desktop cannot leave this test asserting stale values. */
    private val config: ChIndexConfig by lazy {
        val thresholds = fixtures.getJSONObject("thresholds")
        val stop = fixtures.getJSONArray("author_stop")
        ChIndexConfig(
            bucketChars = fixtures.getInt("bucket_chars"),
            titlePrefix = fixtures.getInt("title_prefix"),
            prefixMin = thresholds.getDouble("prefix_min"),
            fullMin = thresholds.getDouble("full_min"),
            fullMissing = thresholds.getDouble("full_missing"),
            fullStrict = thresholds.getDouble("full_strict"),
            authorStop = buildSet { for (i in 0 until stop.length()) add(stop.getString(i)) },
        )
    }

    @Test
    fun normalizationMatchesPython() {
        val cases = fixtures.getJSONArray("similarity")
        assertTrue("expected a meaningful number of cases", cases.length() > 200)
        for (i in 0 until cases.length()) {
            val case = cases.getJSONObject(i)
            assertEquals(
                "normalize(${case.getString("a")})",
                case.getString("normalized_a"),
                ChMatcher.normalize(case.getString("a")),
            )
            assertEquals(
                "normalize(${case.getString("b")})",
                case.getString("normalized_b"),
                ChMatcher.normalize(case.getString("b")),
            )
        }
    }

    @Test
    fun similarityReproducesDifflibRatio() {
        val cases = fixtures.getJSONArray("similarity")
        var worst = 0.0
        var worstCase = ""
        for (i in 0 until cases.length()) {
            val case = cases.getJSONObject(i)
            val a = case.getString("a")
            val b = case.getString("b")
            val delta = Math.abs(ChMatcher.similarity(a, b) - case.getDouble("ratio"))
            if (delta > worst) {
                worst = delta
                worstCase = "a=$a | b=$b"
            }
        }
        assertTrue("worst ratio divergence $worst on $worstCase", worst <= tolerance)
    }

    @Test
    fun prefixSimilarityReproducesDifflibRatio() {
        val cases = fixtures.getJSONArray("similarity")
        // The prefix length the fixtures were generated with is carried by the
        // index, not hardcoded here, so a change on the desktop cannot leave
        // this test quietly asserting the old value.
        val prefix = config.titlePrefix
        var worst = 0.0
        for (i in 0 until cases.length()) {
            val case = cases.getJSONObject(i)
            val delta = Math.abs(
                ChMatcher.similarityPrefix(case.getString("a"), case.getString("b"), prefix) -
                    case.getDouble("prefix_ratio"),
            )
            if (delta > worst) worst = delta
        }
        assertTrue("worst prefix divergence $worst", worst <= tolerance)
    }

    @Test
    fun authorHandlingMatchesPython() {
        val cases = fixtures.getJSONArray("authors")
        assertTrue(cases.length() > 100)
        val stop = config.authorStop
        for (i in 0 until cases.length()) {
            val case = cases.getJSONObject(i)
            val author = case.getString("author")
            assertEquals("flip($author)", case.getString("flipped"), ChMatcher.flipAuthor(author))
            assertEquals("lastToken($author)", case.getString("last_token"), ChMatcher.lastToken(author))
            val expected = case.getJSONArray("tokens").let { array ->
                (0 until array.length()).map { array.getString(it) }.toSortedSet()
            }
            assertEquals(
                "tokens($author)",
                expected.toList(),
                ChMatcher.authorTokens(author, stop).toSortedSet().toList(),
            )
        }
    }

    @Test
    fun acceptanceDecisionsMatchPython() {
        val cases = fixtures.getJSONArray("matches")
        var mismatches = 0
        for (i in 0 until cases.length()) {
            val case = cases.getJSONObject(i)
            val actual = ChMatcher.titleAuthorMatch(
                case.getString("title"),
                case.getString("author"),
                case.getString("cand_title"),
                case.getString("cand_author"),
                config,
            )
            if (actual != case.getBoolean("match")) mismatches++
        }
        assertEquals("acceptance decisions diverging from Python", 0, mismatches)
    }

}
